### ISSUE TITLE
resolve.root path relative to cwd

### ISSUE THREAD

**Issue by joIivier** [benmosher/eslint-import-core#3]
One can read from the doc of resolve.root that:

> Paths may be absolute or relative to the package root (i.e., where your package.json is).

When reading the code, I understand that in fact these paths should be relative to the current working directory when the rule is executed, because in the end the resolution is made via `fs.statSync` at `eslint-import-core/node_modules/resolve/lib/sync.j`s:10 with as argument only the concatenation of the path in this array and the imported file name.

So it works fine in my gulp build because I start it from my root folder where I have my package.json, but it doesnt' work from my IDE for instance because it runs eslint from the folder containing the file to validate.

I couldn't find in eslint documentation what is the cwd supposed to be, so I don't know if the fact that your rule fails on my WebStorm is WebStorm fault for providing an incorrect current path, or is due to the fact that the rule relies incorrectly on the current working directory. Do you have any pointer to resources that have an answer to that?

**Comment by benmosher** [comment]
Ah, yeah. One of my colleagues had a similar problem inside PyCharm, but it was not obvious exactly what the problem is. 

Unfortunately, you're right about the interpretation of the doc for `resolve.root`, but at this point it's probably a bit more optimistic than accurate. 

I have been reflecting on how to solve this in a robust way. Not sure what to do, just yet. 

What do your import statements generally look like? (Or: why do you use resolve.root?)

**Comment by joIivier** [comment]
Hi,
our project structure looks like:
.
├── gulpfile.js
├── node_modules
├── package.json
├── src
│   ├── css
│   ├── images
│   ├── index.html
│   ├── js5
│   ├── js6
│   └── samples
├── tests
│   ├── js5
│   ├── js6
│   └── resources

So we transpile only the content of the js6 folders and we don't want each import path to start by src/js6 or tests/js6 so we use as base the js6 folder before passing our files to traceur which generates the module names we expect.

I opened an issue on WebStorm (https://youtrack.jetbrains.com/issue/WEB-16924)  which they fixed so that they use the correct working directory when running the rules, so for me this is fine now and anyway I am not sure you can do something from within your rule, I think this should be eslint job to enforce the cwd when running the rules.

**Comment by benmosher** [comment]
Ah, great. I will update the docs to indicate that resolve.root is relative to the cwd of ESLint at runtime. Thanks!
